<?php
/**
 * AvailableQuantityResponseV2ResourcesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\QuantitiesV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Available Quantity API
 *
 * Quantities interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace EzzeSiftuz\QuantitiesV2;

/**
 * AvailableQuantityResponseV2ResourcesTest Class Doc Comment
 *
 * @category    Class
 * @description AvailableQuantityResponseV2Resources
 * @package     EzzeSiftuz\QuantitiesV2
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AvailableQuantityResponseV2ResourcesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AvailableQuantityResponseV2Resources"
     */
    public function testAvailableQuantityResponseV2Resources()
    {
    }

    /**
     * Test attribute "variations"
     */
    public function testPropertyVariations()
    {
    }
}
