<?php
/**
 * AvailableQuantityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\Quantitiesv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Available Quantity API
 *
 * Quantities interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\Quantitiesv2;

use EzzeSiftuz\Quantitiesv2\Configuration;
use EzzeSiftuz\Quantitiesv2\ApiException;
use EzzeSiftuz\Quantitiesv2\ObjectSerializer;

/**
 * AvailableQuantityApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\Quantitiesv2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AvailableQuantityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for storeAvailableQuantitiesUsingPOST
     *
     * Update the available quantity for a specific SKU (up to 200 SKUs per request).
     *
     */
    public function testStoreAvailableQuantitiesUsingPOST()
    {
    }
}
