<?php
/**
 * AvailableQuantityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EzzeSiftuz\QuantitiesV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Available Quantity API
 *
 * Quantities interface
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace EzzeSiftuz\QuantitiesV2;

use EzzeSiftuz\QuantitiesV2\Configuration;
use EzzeSiftuz\QuantitiesV2\ApiException;
use EzzeSiftuz\QuantitiesV2\ObjectSerializer;

/**
 * AvailableQuantityApiTest Class Doc Comment
 *
 * @category Class
 * @package  EzzeSiftuz\QuantitiesV2
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AvailableQuantityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getAvailableQuantities
     *
     * Get available quantities for a specific Partner (Upto 200 per request). The partner needs to update the quantities for all his products once or limit the products being returned in the response by setting the limit value to number of products they have updated.
     *
     */
    public function testGetAvailableQuantities()
    {
    }

    /**
     * Test case for getAvailableQuantityBySku
     *
     * Get available quantity for a specific Sku.
     *
     */
    public function testGetAvailableQuantityBySku()
    {
    }

    /**
     * Test case for storeAvailableQuantitiesUsingPOST
     *
     * Update the available quantity for a specific SKU (up to 200 SKUs per request).
     *
     */
    public function testStoreAvailableQuantitiesUsingPOST()
    {
    }
}
